# Generated by Django 3.2.10 on 2022-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField(choices=[(0, 'sunny'), (1, 'Rain'), (3, 'Cloudy'), (4, 'Snow')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
